# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
    -   id: black
        args: ["--check", "--diff"]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args: ["--ignore=E501,E203,W503"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.0
    hooks:
    -   id: mypy
        args: ["--check-untyped-defs"]
        additional_dependencies: ["distro-info>=1.0", "python-debian>=1.0.1", "pytest", "requests>=2.32.5", "launchpadlib>=2.1.0", "termcolor>=3.3.0"]
        exclude: "ubuntu_lint/dput.py"
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: python3 -m pytest --verbose
        language: system
        types: [python]
        pass_filenames: false
