#!/bin/sh
set -e

export TEST_AUTOPKGTEST=1

cp pyproject.toml "$AUTOPKGTEST_TMP"
cp -r tests/ "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for py in $(py3versions --supported); do
    $py -m pytest -v
done
