on: [push, pull_request]
name: QA
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: install dependencies
      run: pip install pytest .
    - uses: pre-commit/action@v3.0.1
